### ISSUE TITLE
xmplayer v0.0.4 Freeze

### ISSUE THREAD

**Issue by emplix** [LibXenonProject/xmplayer#5]
Xbox Revision: TRINITY
NAND Size: 16MB
USB-Drive: External Platinum Hard Drive USB 2.0 500GB
USB-Pen: San Disk Cruzer 16 GB

xmplayer launched with Dashlaunch 3.09 (on root of USB PEN)
Freezed while loading/starting an .mkv file or avi movie from the external hard drive (NTFS)

**Comment by siz-** [comment]
Will the same files load from your usb pen? Is it all video files on external? Did restart help? No red screen, just frooze? Did play a bit or nothing? Does it matter if it's 720p/1080p file, regular xvid SD file? Using AAC codec?

**Comment by emplix** [comment]
Thanks for replying Siz!
all mkv and avi's movies wont loading it just freezes everytime. when im using ffplay it does work. i show you video for better demonstration.
edit:

the files on my usb are also freezin.

http://www.youtube.com/watch?v=AHmfO8vcIvY&feature=player_embedded

here is the codec information from my mkv file.

https://dl.dropboxusercontent.com/u/41969245/codec.html

**Comment by siz-** [comment]
Where is the mplayer folder? and does the mplayer folder contain  the "config" file?

**Comment by emplix** [comment]
the mplayer folder is in the xmplayer v0.0.4 foler on the usb pen. yes it does. 
i just tried to restart xmplayer from the menu and it just shutdown the console. i also tried to launch with the same procedure on the internal xbox root hdd nothing works. When i launched debug xenon.elf it also freezed.

**Comment by emplix** [comment]
Problem solved! Siz gave me a download link with a replaced xenon.elf! Everything works fine.

**Comment by mxi1** [comment]
Hi Siz, can you share the replaced xenon.elf file to me? I met the same issue while trying to play mkv files in xmplayer 0.4 on my xbox360 console. Thank you very much!

**Comment by MahadRafique** [comment]
Hello Siz and emplix, I'd appreciate if anyone of you guyz can share that link with the replaced xenon.elf.
my xmplayer seems to run file but as soon as I select any video format file, xbox freezes..
Thanks..

**Comment by siz-** [comment]
It has been a long time since I worked on it. I'
I will see if I have it lying around. 

Personally I use a raspberry pi with LibreELEC as a media center. Cheap, easy, powerful and extremely well supported.
